### ISSUE TITLE
iPhone Photos Are Upside Down after upload.

### ISSUE THREAD

**Issue by ilakskill** [projectsend/projectsend#427] opened 2017-06-28 16:55 UTC
When uploading a image from a Iphone picture orientation is not correct.

**Comment by lenamtl** [comment] 2017-07-04 17:44
Could do give more information on how to reproduce

**Comment by ilackskills** [comment] 2017-07-05 05:22
I do not have an iPhone to test with so I can not describe exactly the steps needed to reproduce.  From my understanding, it is either missing or incorrect info in the iPhone Picture located in the EXIF metadata.  I will see what I can come up with on this.

**Comment by ilackskills** [comment] 2017-07-06 12:45
@lenamtl I should get some examples today.  But I have noticed Images only display in landscape, not portrait.  I will set up a test account for your review.

**Comment by ilackskills** [comment] 2017-07-06 13:00
![image](https://user-images.githubusercontent.com/15673241/27912065-1edf8682-6221-11e7-8ea6-068d59dfe726.png)

The finger is pointing to the top of the phone, the red arrows are pointing where the sky should be.

**Comment by ilackskills** [comment] 2017-07-14 11:49
I am gonna try and work on this when I get time because this is a big PITA for me.

**Comment by corvinb** [comment] 2017-10-23 03:46
+1

**Comment by ilakskill** [comment] 2018-01-14 18:41
This is from an old version, can't remember what one, I did fix it but overwrote with current version.  I will see if the problem is still there.

**Comment by mschop** [comment] 2018-06-03 08:36
This is an iphone and usage problem and not a bug in ProjectSend. ProjectSend does not manipulate the images or use the meta information for displaying the images. Therefore I close this issue.

**Closed by mschop** 2018-06-03 08:36 UTC
Labels: Investigation
