### ISSUE TITLE
ID of uploader is not possible to identify when file is unassigned

### ISSUE THREAD

**Issue by Lukas-SK** [projectsend/projectsend#263] opened 2016-10-12 16:17 UTC
I have got significant amount of unassigned files for which is not possible to identify client (uploader) due to following:
1. client (uploader) uploaded files -> clicked on the "Upload" button; all files were correctly uploaded
2. on the second screen which occurs just after correct upload (where you can optionally rename files and/or add description) client just closed browser and did not click on the "Continue" button

Due to this fact we get a lot of unassigned files which is not possible to identify on the basis of client ID.

I think this is a major dysfunction because this human error occur really a lot.

**Comment by lenamtl** [comment] 2016-10-12 17:23
We can add a _quit without saving_ detection

**Comment by ignacionelson** [comment] 2016-10-12 17:29
Nice temp solution! Let's do that.

The long term one is to save the file as soon as it's uploaded, which would turn the second page to function the same way as the editor. It would just overwrite the info of the file.
With some more work, a nice side effect would be to finally get rid of the edit file php script, and have it all in one place.

**Comment by Lukas-SK** [comment] 2016-10-12 18:04
Guys, thank you for quick reply. I think as a temporary solution it could be useful.
I could suggest (I do not know which is easier to write) add a column to unassigned documents where will be information about uploader (client). Then you can select (batch selection would be great) files and add it to correct client.

**Comment by ilackskills** [comment] 2016-10-18 16:33
is there a reason we cant assign the uploader when uploaded then come back to edit-file.php to make adjustments?

**Comment by lenamtl** [comment] 2016-10-19 13:05
Because the unassigned files info are not saved in DB.

**Comment by thealiex** [comment] 2016-10-21 15:57
The topic for this issue should be adjusted to better reflect the actual problem.
Below I have pasted what I had posted in the issue I closed.
I know most of it has already been noted in this topic.

From what I've seen the upload process is divided into two steps.
1. File is selected and uploaded to the system. (upload-from-computer.php)
2. File information is edited and added to the database. (upload-process-form.php)

The issue is that if you complete step 1 and upload a file from your computer,
but you do not finish step 2, submitting the upload process form 
then the file is uploaded to the system but is not added to the database leaving an orphaned file on the system.

Suggestions
Alternative 1
Instead I suggest that in the first step the file is selected uploaded and added to the database.
Then in the second step the database file information can be edited.

Alternative 2 (which is probably not easy to manage) is to keep the file in the memory in the first step and not save it until second step is completed.

**Comment by lenamtl** [comment] 2016-10-23 14:09
Nothing should be save in DB before user click on Save.
User may change his mind and cancel at any time.

Just checking if the user try to quit the page before saving is enough.

**Comment by thealiex** [comment] 2016-10-24 20:37
I would say that pressing "Upload" is enough consent to save the image. And then give the user a chance to change the file information in the second step.
The second step could also have a "cancle" or "delete" option in case the user wants to remove the image immediately.

**Comment by Lukas-SK** [comment] 2016-10-24 21:09
Guys for the real work environment as I use it is most crucial that the uploader is identifiable. Currently I am managing 55 clients at once. Each is uploading around 20-50 files per month. For each client there are at least 3 people uploading files. We are talking about more than 165 different persons plenty of which can barely open the browser (yes also this type of persons still exists).

It is not any how possible to track unmatched files. So for real work solution it has to be assigned at the time of upload to client and then they can do changes.

I think to get the real world solution as this seems to be it should consider this situation in design.

**Comment by dannyulman** [comment] 2016-10-25 13:13
My customers are also complaining there files don't show up after they upload a file.
And it's the same problem everybody else is having, They click upload on the first screen and think they are done. Then they close the browser out thinking they are done or just forget and they are none the wiser and I am left with a mess trying to figure out who the file should belong too.
Atleast at the top of the second screen put in medium sized bold red font stating;
"UPLOAD IS NOT COMPLETE YET"
then in smaller black normal type 
"Please click upload button at bottom of page to complete the file upload!"
Use this in addition to warning message upon closing tab or browser.
Better yet I would like it to write to database after first upload page,

**Comment by ilackskills** [comment] 2017-03-15 13:08
I am about to modify this because it is a pain for me as well, I am working on this today, I added another button at the top of the screen for the time being and that is working for now, I see no reason why the files are uploaded but not assigned to the user.  If the user backs out then the files should not be there at all.  I will fix this.

**Comment by ignacionelson** [comment] 2022-11-20 20:33
This should be fixed since all users can see their own files now that they are added to the database as soon as they finish uploading

**Closed by ignacionelson** 2022-11-20 20:33 UTC
Labels: Enhancement
