### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by Mexxwelll** [projectsend/projectsend#912] opened 2021-03-02 19:54 UTC
Hello,

I also would like to have LDAP implemented. I have ProjectSend currently installed and would like to help test. Can you tell me what you need to know in order for me to test?

Thanks in advance.

Kind regards,

Mexxwelll

**Comment by ignacionelson** [comment] 2021-11-30 13:30
Duplicate of #312

**Closed by ignacionelson** 2021-11-30 13:30 UTC
