### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: ../Projectsend/

### ISSUE THREAD

**Issue by david20240** [projectsend/projectsend#690] opened 2019-02-22 11:44 UTC
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request
Hi Projectsend Community,
I discovered this morning this error and I do not know where to modify this into jquery.min.js
Did you ever encounter this kind of error?
Thank you so much for helping me
Have a nice day and thank you so much

```
Uncaught Error: Syntax error, unrecognized expression: ../Projectsend/
    at Function.fa.error (jquery.min.js:2)
    at fa.tokenize (jquery.min.js:2)
    at fa.select (jquery.min.js:2)
    at Function.fa [as find] (jquery.min.js:2)
    at n.fn.init.find (jquery.min.js:2)
    at new n.fn.init (jquery.min.js:2)
    at n (jquery.min.js:2)
    at HTMLAnchorElement.<anonymous> (theme.js:2480)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
```

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1053
* php version: 5.6.40
* MySQL version: 5.5.60

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by ignacionelson** [comment] 2019-04-25 02:33
Could not reproduce, closing. Sorry!
If you can provide any more information, please feel free to open the issue again.

**Closed by ignacionelson** 2019-04-25 02:33 UTC
