### ISSUE TITLE
duplicate files being overwritten

### ISSUE THREAD

**Issue by ghost** [projectsend/projectsend#305] opened 2016-12-02 20:06 UTC
Before when somebody uploaded a file with a duplicate file name projectsend would just add a _1 or _2 and so on to the end of the file instead of overwriting the existing one.
But now files are being overwritten and the customer cant refer back to the old version anymore because its getting overwritten.

How do I make it go back to not overwriting.

**Comment by lenamtl** [comment] 2016-12-03 13:52
Hi,
which version are you using?

**Comment by dannyulman** [comment] 2016-12-04 06:48
version 757

**Comment by zwobbl** [comment] 2016-12-06 13:31
I'm using 754 and also run into this issue. But I have to note, that the overwriting only happens if the uploaded file has a filesize bigger than 1 mebibyte. Files in size up to this magical limit are correctly suffixed with _1, _2 and so on.

Is the upload divided into mebibyte chunks and reassembled on server-side?

**Comment by onlinestatements** [comment] 2016-12-07 19:18
@lenamtl 
Where you able to verify this is actually a bug?

**Comment by lenamtl** [comment] 2016-12-09 02:23
No I didn't have the time to check.
I just put this label because @zwobbl confirmed the problem
what is the size of the file?

**Comment by dannyulman** [comment] 2016-12-09 15:08
I will have to wait until somebody else tries to reupload a duplicate file again

**Comment by zwobbl** [comment] 2016-12-09 15:34
Indeed I'm not somebody else, but I did some more testing. :) I have three installations of ProjectSend to administrate, all on r754 at the moment. Two of them are behind a reverse proxy (one nginx, one apache) running in a vm hosted by kvm. But one is installed on bare-metal without reverse proxy.
It happens on all of them. File bigger then 1MiB are overwritten. So I don't think that it is environment related.

@dannyulman & @lenamtl weren't you able to reproduce this behaviour? and do you see any indication that it has to do something with the 1MiB limit?

**Comment by lenamtl** [comment] 2016-12-09 20:02
Sorry I'm very busy at the moment.
I'm using localserver and share hosting server.

**Comment by zwobbl** [comment] 2016-12-09 20:23
5.6.27 and 5.4.45 running on debian jessie and wheezy

**Comment by zwobbl** [comment] 2016-12-09 20:24
@dannyulman can you also confirm that it only happens with files bigger one mebibyte?

**Comment by onlinestatements** [comment] 2016-12-09 20:31
I will confirm later tonightOn Dec 9, 2016 3:24 PM, Marcel Naziri <notifications@github.com> wrote:@dannyulman can you also confirm that it only happens with files bigger one mebibyte?

**Comment by zwobbl** [comment] 2016-12-09 20:54
I think I wasn't too bad with my guess. Firefox dev tools showed me that the upload is indeed chunked. process_upload.php is called multiple times while uploading bigger files. And I found this [line](https://github.com/ignacionelson/ProjectSend/blob/master/process-upload.php#L52) in the sources. I think filename generation has to be refactored.

**Comment by lenamtl** [comment] 2016-12-10 13:26
I do prefer rename the file on upload with a timestamp as file name, save the real name in BD then on download rename the file with the real name. This is preventing all kind of problem with file name.
This is what I'm using in my other web application.

**Comment by zwobbl** [comment] 2016-12-10 13:52
I would also prefer having the real filename as metadata in the db. maybe instead or in addition to the timestamp some sort of guid should be used.
But I could imagine that this will result in bigger changes in the whole project. Maybe we can discuss how the upload processing itself could be fixed so at least no overwritings will happen anymore.

**Comment by lenamtl** [comment] 2016-12-10 14:03
I have tried several way and this is the only way that prevent all issues with file name.

Using timestamp is unique, so unique filename.
Timestamp have no special characters, no space, no extra extension name, no accentuated characters, so this is preventing a lot of problems.  Specially when you are using latin.

Of course if there are other way, I will be happy to try it.

By experience most user that upload file does not care about file name (and file size).
So we should never trust the user, like we should do it  in form validation.

**Comment by dannyulman** [comment] 2016-12-10 14:05
Adding datestamp to end of filename is most preferable. That what we try to
get our customers to do

**Comment by zwobbl** [comment] 2016-12-10 14:24
concurrent uploads of different users could end up to the same timestamp on very rare conditions. so I would maybe additionally add a hash value over the realfilename and the uploaders id/username.

**Comment by dannyulman** [comment] 2016-12-10 14:26
But different customers use very different filenames. I have never had two
different customers use the same filename let alone at the same time

**Comment by zwobbl** [comment] 2016-12-10 14:40
if I get lenamtl right he proposed to replace the real filename completely with the timestamp to prevent problems with character encodings in the filename. this way the timestamp wouldn't be unique per user or file.

**Comment by onlinestatements** [comment] 2016-12-10 14:58
No. The timestamp should be appended to the end of the filename. It the entire filename was replaced I would have no idea who uploaded the file or which of their many projects each customer uploads. That would be awful and the website would be completely unusable in that condition. I download hundreds of files a day then my program processes them and processes them based on their filename. Like it might look for progdata1*.zip so that allows numbers or data to be appended to the end of the filename. We process variable data and our program converts it to pcl code to send to the printer. The filename cannot be overwritten but can be append to the end of the filename.On Dec 10, 2016 9:40 AM, Marcel Naziri <notifications@github.com> wrote:if I get lenamtl right he proposed to replace the real filename completely with the timestamp to prevent problems with character encodings in the filename. this way the timestamp wouldn't be unique per user or file.

**Comment by lenamtl** [comment] 2016-12-10 19:19
I have worked on several project with file upload.
In my custom application
The way it's working, in the DB we have the real filename, the timestamp so it end something like that  1481335262.png 
On the web page the client see the real name of the file and when he download the file it get renamed so this is transparent to the client.
To gain performance I also save file size and mime type plus each client have their own folder.
If you allow special characters, accent, space in filename you will have issue for sure.

PS actually remove them from file name but the name may become hard to guess.
Let say été.png will be saved as _t_.png

**Comment by onlinestatements** [comment] 2016-12-21 02:37
Any progress on this bug lately?
Thanks

**Comment by zwobbl** [comment] 2016-12-21 16:29
I looked up the code and suggest to move the unique filename generation just before the renaming of the temporary part-file. I've build a [patch](https://gist.github.com/zwobbl/a79a47217528cf8b8f541d90d926457a) for this and was able to test it successfully.

This way it does not solve all issues, e.g. concurrent upload of two users of the same file ending up in mixing them together. But at least overwriting on certain file sizes should have been fixed. So I could live with it ...

**Comment by lenamtl** [comment] 2016-12-22 14:48
Could you give more info about the patch.

**Comment by onlinestatements** [comment] 2017-01-03 17:37
Where do I put this code into from the patch.
What do I replace.
Could you supply the code for the entire php file with the patch in it.
Thanks

**Comment by zwobbl** [comment] 2017-01-04 17:07
oh sorry, copying the patch to gist has eaten up the tabstops, so applying the patch will fail. what is the best or preferred way to provide patches?

**Comment by flipswitchingmonkey** [comment] 2017-01-19 16:10
This is an extremely annoying issue, and potentially very dangerous. Why are we using filenames at all and not just use UUIDs for the files on disk? Alternatively, why do we not at least have subfolders per client inside the upload folder? That way one client at least can't overwrite the other clients stuff.

**Comment by ilackskills** [comment] 2017-02-08 22:17
I just had this happen to me just now.

First image was uploaded by user **A** Tue 1/24/2017 11:12 AM

> 2nd file was image.jpg uploaded by user **B**
>![image](https://cloud.githubusercontent.com/assets/15673241/22759466/2f759a04-ee18-11e6-9446-1358f0acd76f.png)

>3rd File  same file name uploaded by user **C**
> ![image](https://cloud.githubusercontent.com/assets/15673241/22759265/678e1bb0-ee17-11e6-89cc-48acb18de195.png)

> 4th file same file name uploaded by user **D**
> ![image](https://cloud.githubusercontent.com/assets/15673241/22759283/7974ebce-ee17-11e6-8a8d-0630bb951f4e.png)


Only the last file remains but but shows up in 4 different user accounts

![image](https://cloud.githubusercontent.com/assets/15673241/22759859/9ee1a666-ee19-11e6-91e6-74b24b9894a5.png)

**Comment by dannyulman** [comment] 2017-02-08 22:30
Yeah that is really dangerous because my website handles nothing but
medical records. I have been lucky so far that no one has uploaded a
duplicate named file or we would be sued.

**Comment by ilackskills** [comment] 2017-02-08 22:38
yeah its gonna take me a while to dig through but this is something that needs to be address because its not only a issue with writing over images the images relationship is flawed as well.

If user A uploads file.jpg and user B uploads file.jpg both users A and B will see what user B uploaded.

**Comment by ilackskills** [comment] 2017-02-08 22:48
is anyone actively working on this?  short term solution needs to happen pretty soon, on upload filename needs to change to a unique name.

**Comment by Ciscog33k** [comment] 2017-02-08 22:51
@ilackskills The Dev's been MIA since early Jan.  I've reached out to him on several fronts, all of which went nowhere.  I don't think there's going to be any fixes unless you're doing them on your own builds. :(

**Comment by ilackskills** [comment] 2017-02-08 22:55
@Ciscog33k I am not a great coder and still learning my way around this software, I will do my best to resolve this or at least temp fix it in the next few days, I have lost 3 files already.  It sucks but it is open source software and as such stuff like this happens.  I will do my best to help but if anyone else with a little more know how and more knowledgeable on this software could help that would be great.

**Comment by ilackskills** [comment] 2017-02-08 22:56
I am gonna have to clone my server before I can do any work on it, but I will do that tonight and start working on it tomorrow.

**Comment by Ciscog33k** [comment] 2017-02-08 22:56
@ilackskills I'm in the same boat buddy.  This software is literally the only one that meets our needs.  It's really sad.  I'd be willing to pay for this if it was maintained.

**Comment by ilackskills** [comment] 2017-02-08 23:01
That's a true story but since I am gonna be using this I will fix what I have to since I have the ability, a little limited but I can do it.  I have already modified alot to suit my needs. I think I just lost 3 more files. This is gonna be an issue for me.

**Comment by ilackskills** [comment] 2017-02-09 05:13
Temp Fix: **Use at your own risk**

On or around line 78, upload-from-computer.php
Change  chunk_size from 1mb to 0mb


![image](https://cloud.githubusercontent.com/assets/15673241/22770148/cffba226-ee53-11e6-9af3-a9aaa8fb905f.png)

**Comment by zwobbl** [comment] 2017-02-09 12:47
@ilackskills have you tried my patch for this? https://gist.github.com/zwobbl/a79a47217528cf8b8f541d90d926457a
the suffix generation is moved to the point the .part file is renamed to the final filename for saving. so it works for non-chunked and chunked uploads.
It think it is not a final solution, but at least it prevents overwriting at most of the times. Two users uploading file with same filename at the same time will still mix up things, but this is more unlikely.

**Comment by zwobbl** [comment] 2017-02-09 12:52
I would vote for by-user folders where uploaded files are saved. This way even on the filesystem you have some kind of structure of you uploaded stuff and no concurrent uploads of different users could happen.

**Comment by ilackskills** [comment] 2017-02-09 13:00
@zwobbl I have not tried it, I will give it a spin now, as far as directories per user dont see why that would not work well and should not be too hard to implement.

**Comment by ilackskills** [comment] 2017-02-09 13:22
@zwobbl Yes thats a problem I would have working on this, what I am working on is a mix of different versions plus my customization's, so it will not mix well with others.  I do not really have the time to work on a fresh install and mod from there then modify the code I use.

shouldnt you rename the file in file-upload.php

**Comment by ilackskills** [comment] 2017-02-09 13:38
- [ ] batch create current user directories
- [ ] batch move files to correct folders
- [ ] batch update DB with new file location so you dont need to edit many pages
- [ ] edit upload so it saves to user dir
- [ ] create dir on user create

**Comment by zwobbl** [comment] 2017-02-09 13:48
haven't looked up file-upload.php yet. There is the method upload_move that is connected with upload-process-form.php. Don't know what happens there. Is it possible to change filename on the upload assignment form?

**Comment by zwobbl** [comment] 2017-02-09 13:50
@ilackskills 
>  create dir on user create

I would prefer user-dir creation on upload. So you don't have empty folders for read-only users.

**Comment by ilackskills** [comment] 2017-02-09 13:56
@zwobbl I think that would be alot more work than its worth.  Im gonna go ahead and fork this and do a clean install, I dont really know how to use get hub all that well, but I will fork this and at least it will show the changes made on mine.  I have done alot of adds to mine with image previews and other things.  But alot of it is modded to my needs.

**Comment by ilackskills** [comment] 2017-02-09 14:05
https://github.com/ilackskills/ProjectSend/

**Comment by ignacionelson** [comment] 2017-05-01 13:21
I think that the best course of action would be, as some of you previously described, to add the timestamp to the filename, but remove that part when downloading the file. some of that seems to be resolved by the code samples you provided, the only part left alone is when downloading multiple files as zip.

**Comment by ignacionelson** [comment] 2017-05-01 13:30
Also, the user id is a great addition to the filename, just in case. Would have to workout a method of detecting if a file was uploaded before or after this change to not mess with existing ones during download.

**Comment by ignacionelson** [comment] 2017-05-03 21:05
This should be fixed on commit 4a2e3b5
Can anyone give it a try please?

"On the database 2 values are saved now. The original filename (column ORIGINAL_URL) which will be used to save the file during downloads and the filename on disk (column URL) used to reference the file. The new
filename on disk is composed of:
{timestamp}-{sha1 of uploader's username}-{sanitized original filename}.extension"

**Closed** 2022-11-19 19:55 UTC
Labels: Bug, Enhancement
