### ISSUE TITLE
File mark as hidden,  clients cannot see the file

### ISSUE THREAD

**Issue by ericbeaucourt** [projectsend/projectsend#232] opened 2016-09-24 09:26 UTC
I use projectsend for a while and I was very enthousiast. Recently I updated the program with the last version. All my data were perfectly saved. When I upload new files and assign them to a group or client, the group nor the person can see the files. As administrator I can perfectly see the files. Can somebody help me please ?

**Comment by ericbeaucourt** [comment] 2016-09-24 14:57
I did further research myself and the cause of the problem seems the following. When you mark a file the first time as hidden (to send no notifications) the client nor the group can't see the file. Even when you delete the assignations and renew the assignations the client nor the group can't see the file.
I will make an overview of the probleem with screenshots, so the bug (I think that it is a bug) can be resolved

**Comment by ericbeaucourt** [comment] 2016-09-26 06:19
I saw that you marked the problem as a bug, so an overwiew seems no longer necessary. When you marked the file the first time as hidden, you can solve the problem temporarily as follows. Delete the file, upload the file again and then assign the file to  a person or group, without marking the file as hidden. Thanks for all the work. It remains a very good program.

**Comment by lenamtl** [comment] 2016-09-26 10:50
I think this is a bug since you should be able to assign the file later....

**Comment by ericbeaucourt** [comment] 2016-09-26 12:09
You are certainly right because in a previous version you could assign a person or group and mark the file as hidden so there was no mail notification but the person or group could see the file. This works not, as said, in this version. Is there a raison why the bug label is removed ?

**Comment by lenamtl** [comment] 2016-09-26 16:34
Sorry I was not  not sure if it a real bug, I put back the bug label.

Honestly I never really understand completely this feature ... See my question #66

**Comment by olimax** [comment] 2017-07-14 13:02
This still seems to be an issue
As admin if  I mark as hidden on upload, no notifications go out and the assigned client cannot see the file.
If I go to the list of clients and look at that client's files it is marked as hidden.
When I then go to to edit the file there are two options
_"Mark as hidden (will not send notifications) for new assigned clients and groups."_
&
_"Hide from every already assigned clients and groups. "_
Neither are ticked and I am unable to unhide the file 

I am not entirely sure if it is useful to be able to hide from assigned clients. 
personally I think it would be much more useful if this just prevented notifications going out
Less confusion and simpler too

**Comment by rbandak** [comment] 2018-08-06 05:04
I agree with olimax, and I see that with version r1053 still the issue is the same.

**Comment by deklica** [comment] 2018-10-15 15:38
Yes, the bug is still there :(
Can't silently assign a file to the client without notifying him...

**Comment by emkelley** [comment] 2018-11-05 15:02
Confirming that the bug is still present on r1053

**Comment by jeffkshaw** [comment] 2019-04-10 13:55
I am also seeing this problem on r1053. I would like to add files without generating email notifications, but for the files to be there when the users sign in.

**Comment by jeffkshaw** [comment] 2019-04-10 14:21
I was able to resolve this by connecting to the SQL server, manually editing the XXXXX**files_relations** table and **changing the "hidden" value from 1 to 0**.  Would be nice to be able to do this for each file via the web.

**Comment by ignacionelson** [comment] 2020-11-09 01:00
A panel to edit the visibility of current relations will be added in the next version

**Closed** 2022-11-20 23:39 UTC
Labels: Bug, Investigation
