### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kylegordon** [projectsend/projectsend#300] opened 2016-11-22 10:40 UTC
Docker support does not appear to be present. The top hit on Google suggests that https://bitbucket.org/Judge82/docker_projectsend is available, but it does Docker wrongly by running git pull internally on every startup. It does not guarantee consistency or stability in any way.

I maintain a Docker PR at https://github.com/ignacionelson/ProjectSend/pull/296  that I believe is more correct. Is this something that the project would be interested in?

**Comment by Mactory** [comment] 2016-11-22 11:10
I am interested in using docker to deploy ProjectSend, as it makes the installation so much easier. I was already thinking about building my own docker image.

**Comment by kylegordon** [comment] 2016-11-22 11:31
@Mactory Please give my fork or Docker image a shot and tell me where it breaks :-)

**Comment by Mactory** [comment] 2016-11-22 13:54
At the moment I'm busy with other stuff, but I'll definitely give it a try and report back.

**Comment by Mactory** [comment] 2016-12-16 13:25
So, I just had a look at your dockerfile. If I understand it correctly, the source code for ProjectSend is downloaded on the first run of the container.
Isn't the best practice for docker to have one container per Source-Version tagged with the contained version number? This would allow people to install a specific version of ProjectSend instead of only the newest one.

**Comment by Mactory** [comment] 2016-12-22 09:22
I am currently working on my own docker image that contains nginx, mariadb, php5-fpm and the projectsend source ready to go.
So far it is looking good. The db is created and the db connection information is automatically set in project send. Project send starts up nicely but I currently have problems with uploads that seem to be working, but the files never reach the server though they are processed by nginx. I'll report back when I have more information.

**Comment by ravensorb** [comment] 2020-05-17 09:54
Any update on an official docker container?

**Comment by mooboxer** [comment] 2020-08-24 10:21
There is an excellent Docker image already available on Docker-Hub - linuxserver/projectsend

I'm using it behind a reverse proxy and I'm totally satisfied with it.

**Comment by kylegordon** [comment] 2020-08-24 11:45
I appreciate I opened this request 4 years ago, so things may have changed.

My last experience of linuxserver docker images were ones that did a git pull on startup, which tainted my view of their docker images. Do they operate as an expected docker image these days?

**Comment by ignacionelson** [comment] 2020-08-24 15:01
There's a big issue regarding those kind of images that I will try to solve ASAP. In my ignorance of the full possibilities of git and methodologies like git flow, I've always used the repo in a very basic way, only as a "code bucket" and not as intended. That lead to the master branch being a mix of code that works and doesn't... always being the branch that I commit to. So, if a Docker image clones the repo, the result will be that of a code that's mostly broken.
I will create a develop branch, and leave master alone so it can still be used to pull the current released version.
I hope nothing else breaks in the process!

**Comment by ignacionelson** [comment] 2020-09-05 16:17
Master branch is now at r1070 and the release is here https://github.com/projectsend/projectsend/releases/tag/r1070

**Comment by mrays** [comment] 2020-09-10 15:55
Why should use a composer? I like installation in previous release.

**Comment by ignacionelson** [comment] 2020-09-10 16:15
@mrays Composer and node dependencies will be included in the release, so the installation method should not change at all.
Separating the public root from the app itself would be a step forward in terms of security, but will make installation harder. That's how the refactored version is shaping up, but I'm always trying to find ways to simplify this as much as possible.

**Comment by sgoetsch** [comment] 2021-01-14 09:50
As the linuxserver/projectsend image always seems to be a little bit behind, we created our own image https://hub.docker.com/r/terrestris/projectsend
I'll try to keep it up to date, it's a pretty simple config.

**Comment by ignacionelson** [comment] 2021-01-14 16:31
@sgoetsch Thanks! I'll add a link to it in projectsend.org as soon as I can

**Closed** 2023-01-24 23:31 UTC
Labels: Enhancement
