### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by fubian** [projectsend/projectsend#647] opened 2018-11-03 11:44 UTC
## Bug Report

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[ ] Feature request

### Description of the problem

I just cloned a current copy from this repository and tried to install the application on my local server (XAMPP for Linux 7.2.11): http://localhost/projectsend/install/

The result is here:
```

Warning: require_once(/[...]/projectsend/vendor/autoload.php): failed to open stream: No such file or directory in /[...]/projectsend/bootstrap.php on line 22

Fatal error: require_once(): Failed opening required '/[...]/projectsend/vendor/autoload.php' (include_path='.:/opt/lampp/lib/php') in /[...]/projectsend/bootstrap.php on line 22
```

### List the steps to reproduce the issue

1. https://github.com/projectsend/projectsend.git
2. Create new mysql DB
3. Rename config/config.sample.php to config.php and set your database info there.
4. Open browser with url localhost/projectsend/install

### Environment

* ProjectSend version: git hash _bb9b974178c1a7349c012b16fae1f07074baa95c_
* php version: PHP/7.2.11
* MySQL version: 10.1.36-MariaDB

**Comment by mschop** [comment] 2018-11-03 19:16
@fubian If you directly use this the repository and not the build, the dependencies are not loaded by composer. Please install composer (see https://getcomposer.org) and run the command `composer install` in the directory, where the composer.json is located.

Closing, as this is not a bug but intended behavior.

Best Regards
mschop

**Closed by mschop** 2018-11-03 19:16 UTC

**Comment by alexmayo** [comment] 2018-12-11 21:47
This should be put in docs :)
