### ISSUE TITLE
HTML Email Converts To Plain Text When I Send

### ISSUE THREAD

**Issue by Zodyart** [projectsend/projectsend#1091] opened 2022-05-03 01:12 UTC
Not sure why this is happening, but when i installed on docker it was fine before. Now I install it on cyberpanel I have this issue where it converts html email to plain text.

**Comment by ignacionelson** [comment] 2022-11-20 20:43
Couldn't reproduce, sorry. Closing the issue since I believe it was server-related

**Closed as completed by ignacionelson** 2022-11-20 20:43 UTC
Labels: Investigation, Low Priority
